name: workflow w/o docker

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  simple_build:
    runs-on: ubuntu-latest
    env:
      PSQL_USERNAME: gerardo_partida
      PSQL_PASS: Trif0rce
      PSQL_DBNAME: gerardo_partidadb
      JWT_TOKEN_TIME: "120"
      PSQL_HOST: localhost
      PSQL_PORT: 5432 
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.PSQL_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.PSQL_PASS }}
          POSTGRES_DB: ${{ env.PSQL_DBNAME }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Make migrations users
        run: python manage.py makemigrations users
      - name: Run migrations
        run: python manage.py migrate
      - name: Make migrations books
        run: python manage.py makemigrations users
      - name: Run migrations 2
        run: python manage.py migrate
      - name: Run tests
        run: pytest